// @author DARKOLARASLOWED

package pck_calculadora;

import javax.swing.JOptionPane;

public class Calculadora extends javax.swing.JFrame {
   
    public Calculadora() {
        initComponents();
    }
   
    public String operaciones(int operador) {
        double primerValor = 0, segundoValor = 0, resultado;
        boolean band = false;
        try { 
            double auxPrimerValor = Double.parseDouble(PrimerNumero_TextField.getText());
            primerValor = auxPrimerValor;
        } catch (NullPointerException e) {
            band = true;
            JOptionPane.showMessageDialog(null, "El primer numero es necesario para el calculo.", "Error", JOptionPane.ERROR_MESSAGE);
            PrimerNumero_TextField.setText("");
            PrimerNumero_TextField.requestFocus();
        } catch (NumberFormatException e) {
            band = true;
            JOptionPane.showMessageDialog(null, "Solo se aceptan entradas numericas en el primer numero.", "Error", JOptionPane.ERROR_MESSAGE);
            PrimerNumero_TextField.setText("");
            PrimerNumero_TextField.requestFocus();
        }
        try {
            segundoValor = Double.parseDouble(SegundoNumero_TextField.getText());
        } catch (NullPointerException e) {
            band = true;
            JOptionPane.showMessageDialog(null, "El segundo numero es necesario para el calculo.", "Error", JOptionPane.ERROR_MESSAGE);
            SegundoNumero_TextField.setText("");
            SegundoNumero_TextField.requestFocus();
        } catch (NumberFormatException e) {
            band = true;
            JOptionPane.showMessageDialog(null, "Solo se aceptan entradas numericas en el segundo numero.", "Error", JOptionPane.ERROR_MESSAGE);
            SegundoNumero_TextField.setText("");
            SegundoNumero_TextField.requestFocus();
            
        }
        
        if (operador == 4 && segundoValor == 0) {
            JOptionPane.showMessageDialog(null, "No se puede dividir por 0", "Fallo de Sintaxis", JOptionPane.ERROR_MESSAGE);
            return "SINTAX ERROR";
        }
        
        
        if (segundoValor == 0 && operador == 6) {
            JOptionPane.showMessageDialog(null, "No existe el modulo 0 de un numero", "Fallo de Sintaxis", JOptionPane.ERROR_MESSAGE);
            return "Sintax Error";
        }
        
        if (band) {
            return "Sintax Error";
        }
        
        resultado = switch (operador) {
            case 1 -> primerValor + segundoValor;
            case 2 -> primerValor - segundoValor;
            case 3 -> primerValor * segundoValor;
            case 4 -> primerValor / segundoValor;
            case 5 -> (primerValor / 100) * segundoValor;
            case 6 -> primerValor % segundoValor;
            default -> 0;
        };
        
        return String.format("%.2f", resultado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Calculadora_Panel = new javax.swing.JPanel();
        Multiplicacion = new javax.swing.JButton();
        Division = new javax.swing.JButton();
        Suma = new javax.swing.JButton();
        Resta = new javax.swing.JButton();
        Porcentaje = new javax.swing.JButton();
        Modulo = new javax.swing.JButton();
        Calculadora_Label = new javax.swing.JLabel();
        Primernumero_Label = new javax.swing.JLabel();
        SegundoNumero_Label = new javax.swing.JLabel();
        PrimerNumero_TextField = new javax.swing.JTextField();
        SegundoNumero_TextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultado_TextArea = new javax.swing.JTextArea();
        Resultado_Label = new javax.swing.JLabel();
        LimpiarBoton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Calculadora_Panel.setFocusCycleRoot(true);
        Calculadora_Panel.setFont(new java.awt.Font("Mononoki Nerd Font", 3, 24)); // NOI18N
        Calculadora_Panel.setName(""); // NOI18N
        Calculadora_Panel.setOpaque(false);

        Multiplicacion.setFont(new java.awt.Font("Mononoki Nerd Font", 3, 24)); // NOI18N
        Multiplicacion.setText("*");
        Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicacionActionPerformed(evt);
            }
        });

        Division.setFont(new java.awt.Font("Mononoki Nerd Font", 3, 24)); // NOI18N
        Division.setText("/");
        Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionActionPerformed(evt);
            }
        });

        Suma.setFont(new java.awt.Font("Mononoki Nerd Font", 3, 24)); // NOI18N
        Suma.setText("+");
        Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumaActionPerformed(evt);
            }
        });

        Resta.setFont(new java.awt.Font("Mononoki Nerd Font", 3, 24)); // NOI18N
        Resta.setText("-");
        Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaActionPerformed(evt);
            }
        });

        Porcentaje.setFont(new java.awt.Font("Mononoki Nerd Font", 3, 24)); // NOI18N
        Porcentaje.setText("%");
        Porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorcentajeActionPerformed(evt);
            }
        });

        Modulo.setFont(new java.awt.Font("Mononoki Nerd Font", 3, 24)); // NOI18N
        Modulo.setText("M");
        Modulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModuloActionPerformed(evt);
            }
        });

        Calculadora_Label.setFont(new java.awt.Font("Mononoki Nerd Font", 3, 24)); // NOI18N
        Calculadora_Label.setForeground(new java.awt.Color(255, 204, 51));
        Calculadora_Label.setText("CALCULADORA");

        Primernumero_Label.setText("Primer Numero");

        SegundoNumero_Label.setText("Segundo Numero");

        PrimerNumero_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimerNumero_TextFieldActionPerformed(evt);
            }
        });

        SegundoNumero_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundoNumero_TextFieldActionPerformed(evt);
            }
        });

        Resultado_TextArea.setEditable(false);
        Resultado_TextArea.setColumns(20);
        Resultado_TextArea.setRows(5);
        jScrollPane1.setViewportView(Resultado_TextArea);

        Resultado_Label.setText("Resultado");

        LimpiarBoton.setText("CE");
        LimpiarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Calculadora_PanelLayout = new javax.swing.GroupLayout(Calculadora_Panel);
        Calculadora_Panel.setLayout(Calculadora_PanelLayout);
        Calculadora_PanelLayout.setHorizontalGroup(
            Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                .addGroup(Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                        .addComponent(Resultado_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Calculadora_PanelLayout.createSequentialGroup()
                        .addGroup(Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Calculadora_Label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Primernumero_Label, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Calculadora_PanelLayout.createSequentialGroup()
                        .addComponent(SegundoNumero_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SegundoNumero_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PrimerNumero_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                            .addComponent(Multiplicacion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Division))
                        .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                            .addComponent(Porcentaje)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Modulo)))
                    .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                        .addComponent(Resta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Suma))
                    .addComponent(LimpiarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        Calculadora_PanelLayout.setVerticalGroup(
            Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                .addComponent(Calculadora_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Primernumero_Label)
                    .addComponent(PrimerNumero_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Multiplicacion)
                    .addComponent(Division))
                .addGap(18, 18, 18)
                .addGroup(Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                        .addGroup(Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SegundoNumero_Label)
                            .addComponent(SegundoNumero_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(Resultado_Label))))
                    .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                        .addGroup(Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Resta)
                            .addComponent(Suma))
                        .addGap(18, 18, 18)
                        .addGroup(Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Porcentaje)
                            .addComponent(Modulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LimpiarBoton)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Calculadora_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Calculadora_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        Calculadora_Panel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaActionPerformed
        Resultado_TextArea.setText(operaciones(1));
    }//GEN-LAST:event_SumaActionPerformed

    private void PorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorcentajeActionPerformed
        Resultado_TextArea.setText(operaciones(5));
    }//GEN-LAST:event_PorcentajeActionPerformed

    private void PrimerNumero_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimerNumero_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrimerNumero_TextFieldActionPerformed

    private void MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicacionActionPerformed
        Resultado_TextArea.setText(operaciones(3));
    }//GEN-LAST:event_MultiplicacionActionPerformed

    private void ModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModuloActionPerformed
        Resultado_TextArea.setText(operaciones(6));
    }//GEN-LAST:event_ModuloActionPerformed

    private void RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaActionPerformed
        Resultado_TextArea.setText(operaciones(2));
    }//GEN-LAST:event_RestaActionPerformed

    private void DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionActionPerformed
        Resultado_TextArea.setText(operaciones(4));
    }//GEN-LAST:event_DivisionActionPerformed

    private void SegundoNumero_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundoNumero_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SegundoNumero_TextFieldActionPerformed

    private void LimpiarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarBotonActionPerformed
        PrimerNumero_TextField.setText("");
        SegundoNumero_TextField.setText("");
        Resultado_TextArea.setText("");
    }//GEN-LAST:event_LimpiarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Calculadora_Label;
    private javax.swing.JPanel Calculadora_Panel;
    private javax.swing.JButton Division;
    private javax.swing.JButton LimpiarBoton;
    private javax.swing.JButton Modulo;
    private javax.swing.JButton Multiplicacion;
    private javax.swing.JButton Porcentaje;
    private javax.swing.JTextField PrimerNumero_TextField;
    private javax.swing.JLabel Primernumero_Label;
    private javax.swing.JButton Resta;
    private javax.swing.JLabel Resultado_Label;
    private javax.swing.JTextArea Resultado_TextArea;
    private javax.swing.JLabel SegundoNumero_Label;
    private javax.swing.JTextField SegundoNumero_TextField;
    private javax.swing.JButton Suma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
