// @author DARKOLARASLOWED

package pck_calculadora;

import javax.swing.JOptionPane;

public class Calculadora extends javax.swing.JFrame {
   
    public Calculadora() {
        initComponents();
    }
   
    public String operaciones() {
        double primerValor = 0, resultado = 0;
        boolean band = false;
        try { 
            double auxPrimerValor = Double.parseDouble(PrimerNumero_TextField.getText());
            primerValor = auxPrimerValor;
        } catch (NullPointerException e) {
            band = true;
            JOptionPane.showMessageDialog(null, "El primer numero es necesario para el calculo.", "Error", JOptionPane.ERROR_MESSAGE);
            PrimerNumero_TextField.setText("");
            PrimerNumero_TextField.requestFocus();
        } catch (NumberFormatException e) {
            band = true;
            JOptionPane.showMessageDialog(null, "Solo se aceptan entradas numericas en el primer numero.", "Error", JOptionPane.ERROR_MESSAGE);
            PrimerNumero_TextField.setText("");
            PrimerNumero_TextField.requestFocus();
        }
        
        if (band) {
            return "Sintax Error";
        }
        resultado = Math.pow(primerValor, 2);
        return String.format("%.2f", resultado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Calculadora_Panel = new javax.swing.JPanel();
        Calculadora_Label = new javax.swing.JLabel();
        Primernumero_Label = new javax.swing.JLabel();
        PrimerNumero_TextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultado_TextArea = new javax.swing.JTextArea();
        Resultado_Label = new javax.swing.JLabel();
        LimpiarBoton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Calculadora_Panel.setFocusCycleRoot(true);
        Calculadora_Panel.setFont(new java.awt.Font("Mononoki Nerd Font", 3, 24)); // NOI18N
        Calculadora_Panel.setName(""); // NOI18N
        Calculadora_Panel.setOpaque(false);

        Calculadora_Label.setFont(new java.awt.Font("Mononoki Nerd Font", 3, 24)); // NOI18N
        Calculadora_Label.setForeground(new java.awt.Color(255, 204, 51));
        Calculadora_Label.setText("CALCULADORA EXPONENCIAL");

        Primernumero_Label.setText("Primer Numero");

        PrimerNumero_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimerNumero_TextFieldActionPerformed(evt);
            }
        });

        Resultado_TextArea.setEditable(false);
        Resultado_TextArea.setColumns(20);
        Resultado_TextArea.setRows(5);
        jScrollPane1.setViewportView(Resultado_TextArea);

        Resultado_Label.setText("Resultado");

        LimpiarBoton.setText("Calcular");
        LimpiarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Calculadora_PanelLayout = new javax.swing.GroupLayout(Calculadora_Panel);
        Calculadora_Panel.setLayout(Calculadora_PanelLayout);
        Calculadora_PanelLayout.setHorizontalGroup(
            Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                .addGroup(Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Calculadora_PanelLayout.createSequentialGroup()
                        .addGroup(Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Calculadora_Label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Primernumero_Label, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PrimerNumero_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(211, 211, 211))
            .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                .addComponent(Resultado_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(LimpiarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        Calculadora_PanelLayout.setVerticalGroup(
            Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                .addComponent(Calculadora_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Primernumero_Label)
                    .addComponent(PrimerNumero_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Resultado_Label))
                    .addGroup(Calculadora_PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Calculadora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LimpiarBoton)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Calculadora_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Calculadora_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        Calculadora_Panel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrimerNumero_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimerNumero_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrimerNumero_TextFieldActionPerformed

    private void LimpiarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarBotonActionPerformed
        Resultado_TextArea.setText(operaciones());
    }//GEN-LAST:event_LimpiarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Calculadora_Label;
    private javax.swing.JPanel Calculadora_Panel;
    private javax.swing.JButton LimpiarBoton;
    private javax.swing.JTextField PrimerNumero_TextField;
    private javax.swing.JLabel Primernumero_Label;
    private javax.swing.JLabel Resultado_Label;
    private javax.swing.JTextArea Resultado_TextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
